.PHONY: clean All

All:
	@echo "----------Building project:[ Stijn_Project - Debug ]----------"
	@cd "Stijn_Project" && "$(MAKE)" -f  "Stijn_Project.mk"
clean:
	@echo "----------Cleaning project:[ Stijn_Project - Debug ]----------"
	@cd "Stijn_Project" && "$(MAKE)" -f  "Stijn_Project.mk" clean
