.PHONY: clean All

All:
	@echo "----------Building project:[ Jari_Project - Debug ]----------"
	@cd "Jari_Project" && "$(MAKE)" -f  "Jari_Project.mk"
clean:
	@echo "----------Cleaning project:[ Jari_Project - Debug ]----------"
	@cd "Jari_Project" && "$(MAKE)" -f  "Jari_Project.mk" clean
