.PHONY: clean All

All:
	@echo "----------Building project:[ Cumpus_Humpus - Debug ]----------"
	@cd "Cumpus_Humpus" && "$(MAKE)" -f  "Cumpus_Humpus.mk"
clean:
	@echo "----------Cleaning project:[ Cumpus_Humpus - Debug ]----------"
	@cd "Cumpus_Humpus" && "$(MAKE)" -f  "Cumpus_Humpus.mk" clean
