.PHONY: clean All

All:
	@echo "----------Building project:[ Hunt_Wumpus - Debug ]----------"
	@cd "Hunt_Wumpus" && "$(MAKE)" -f  "Hunt_Wumpus.mk"
clean:
	@echo "----------Cleaning project:[ Hunt_Wumpus - Debug ]----------"
	@cd "Hunt_Wumpus" && "$(MAKE)" -f  "Hunt_Wumpus.mk" clean
